-- MySQL Script generated by MySQL Workbench
-- Wed May 21 19:40:55 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controleAcademico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controleAcademico` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `controleAcademico` ;

-- -----------------------------------------------------
-- Table `controleAcademico`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`cargos` (
  `idCargos` INT NOT NULL,
  `cargo` VARCHAR(45) NULL COMMENT 'ex. Professor do magistério superio' /* comment truncated */ /*
Assistente adm
...
*/,
  `regValido` TINYINT(1) NULL,
  PRIMARY KEY (`idCargos`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `controleAcademico`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`jornada` (
  `idJornada` INT NOT NULL AUTO_INCREMENT COMMENT '40 horas DE' /* comment truncated */ /*20 horas
substituto
visitante	*/,
  `jornada` VARCHAR(45) NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idJornada`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`situacaoServidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`situacaoServidor` (
  `idSituacaoServidor` INT NOT NULL COMMENT 'Ativo' /* comment truncated */ /*Afastado
Removido
...
*/,
  `situacao` VARCHAR(45) NULL COMMENT 'Ativo' /* comment truncated */ /*Removido
Licença Maternidade
Licença Formação
...
*/,
  `dataEntrada` DATETIME NULL COMMENT 'para o caso de afastamento',
  `dataSaida` DATETIME NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idSituacaoServidor`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `controleAcademico`.`nivelServidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`nivelServidor` (
  `idNivelServidor` INT NOT NULL,
  `nivel` VARCHAR(45) NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idNivelServidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`servidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`servidores` (
  `siape` CHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(60) NOT NULL,
  `observacao` TEXT NULL,
  `quemSubstitui` CHAR(7) NULL COMMENT 'indicar docente que será substituid' /* comment truncated */ /*
*/,
  `idCargo` INT NOT NULL,
  `idJornada` INT NOT NULL,
  `idSituacaoServidor` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `fone1` CHAR(15) NULL,
  `fone2` CHAR(15) NULL,
  `endereco` VARCHAR(60) NULL,
  `cidade` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `idNivelServidor` INT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`siape`),
  INDEX `cargo_idx` (`idCargo` ASC),
  INDEX `jornada_idx` (`idJornada` ASC),
  INDEX `situacao_idx` (`idSituacaoServidor` ASC),
  INDEX `quemSubstitui_idx` (`quemSubstitui` ASC),
  INDEX `fk_servidores_nivel1_idx` (`idNivelServidor` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`nivelCursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`nivelCursos` (
  `idNivelCursos` INT NOT NULL AUTO_INCREMENT COMMENT 'graduação, especializaç' /* comment truncated */ /*�o,
 mestrado, doutorado.*/,
  `nivel` VARCHAR(45) NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idNivelCursos`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`cursos` (
  `codCurso` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `idNivelCursos` INT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codCurso`),
  INDEX `nivel_idx` (`idNivelCursos` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`dominios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`dominios` (
  `idDominio` INT NOT NULL,
  `dominio` VARCHAR(45) NULL COMMENT 'Específic' /* comment truncated */ /*
Conexo
Comum
*/,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDominio`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `controleAcademico`.`ccrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`ccrs` (
  `codCcr` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cHoraria` SMALLINT NULL,
  `idDominio` INT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codCcr`),
  INDEX `dominio_idx` (`idDominio` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`cursosCcrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`cursosCcrs` (
  `codCcr` INT NOT NULL,
  `codCurso` INT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codCcr`, `codCurso`),
  INDEX `fk_cursosCcrs_cursos1_idx` (`codCurso` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `controleAcademico`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`salas` (
  `numBloco` VARCHAR(1) NOT NULL,
  `numSala` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`numBloco`, `numSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`diaSemana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`diaSemana` (
  `idSemana` INT NOT NULL,
  `idDia` INT NOT NULL,
  `dia` VARCHAR(45) NULL,
  `semana` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemana`, `idDia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`periodos` (
  `idPeriodo` INT NOT NULL,
  `idSubPeriodo` INT NOT NULL,
  `periodo` VARCHAR(45) NULL,
  `horaInicio` TIME NULL,
  `horaFim` TIME NULL,
  PRIMARY KEY (`idPeriodo`, `idSubPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`horarios` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `idSemana` INT NOT NULL,
  `idDia` INT NOT NULL,
  `idPeriodo` INT NOT NULL,
  `idSubPeriodo` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horarios_DiaSemana1` (`idSemana` ASC, `idDia` ASC),
  INDEX `fk_Horarios_Periodos1` (`idPeriodo` ASC, `idSubPeriodo` ASC),
  CONSTRAINT `fk_Horarios_DiaSemana1`
    FOREIGN KEY (`idSemana` , `idDia`)
    REFERENCES `controleAcademico`.`diaSemana` (`idSemana` , `idDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_Periodos1`
    FOREIGN KEY (`idPeriodo` , `idSubPeriodo`)
    REFERENCES `controleAcademico`.`periodos` (`idPeriodo` , `idSubPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`alocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`alocacao` (
  `idAlocacao` INT NOT NULL AUTO_INCREMENT,
  `numBloco` VARCHAR(1) NOT NULL,
  `numSala` INT NOT NULL,
  `idHorario` INT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAlocacao`),
  INDEX `fk_Salas_has_Horarios_Horarios1` (`idHorario` ASC),
  INDEX `fk_Salas_has_Horarios_Salas1` (`numBloco` ASC, `numSala` ASC),
  CONSTRAINT `fk_Salas_has_Horarios_Salas1`
    FOREIGN KEY (`numBloco` , `numSala`)
    REFERENCES `controleAcademico`.`salas` (`numBloco` , `numSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salas_has_Horarios_Horarios1`
    FOREIGN KEY (`idHorario`)
    REFERENCES `controleAcademico`.`horarios` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleAcademico`.`servidorCursoCcr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`servidorCursoCcr` (
  `anoSemestre` CHAR(8) NOT NULL COMMENT 'ex. 2014.1, 2014.2',
  `codCcr` INT NOT NULL,
  `codCurso` INT NOT NULL,
  `siape` CHAR(7) NOT NULL,
  `alocacao` INT NULL,
  `observacoes` TEXT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`anoSemestre`, `codCcr`, `codCurso`, `siape`),
  INDEX `fk_ServidorCursoCcr_cursosCcrs1_idx` (`codCcr` ASC, `codCurso` ASC),
  INDEX `fk_ServidorCursoCcr_servidores1_idx` (`siape` ASC),
  INDEX `fk_ServidorCursoCcr_Salas_has_Horarios1` (`alocacao` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `controleAcademico`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`funcao` (
  `idFuncao` INT NOT NULL,
  `funcao` VARCHAR(45) NULL COMMENT 'Ex. Coordenador de laboratóri' /* comment truncated */ /*
*/,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idFuncao`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `controleAcademico`.`servidoresFuncoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleAcademico`.`servidoresFuncoes` (
  `idFuncao` INT NOT NULL COMMENT 'três chaves para que o servidor possa retornar ao cargo varias vezes em períodos diferente' /* comment truncated */ /*.
*/,
  `siape` CHAR(7) NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataSaida` DATETIME NULL,
  `cargaHoraria` TINYINT NOT NULL,
  `regValido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idFuncao`, `siape`, `dataInicio`),
  INDEX `idFuncao_idx` (`idFuncao` ASC),
  INDEX `siape_idx` (`siape` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
